version: '3'
volumes:
  elections:
services:
  sandbox:
    build: .
    image: accountapp:latest
    volumes:
      - elections:/var/log/accountapp/elections
    depends_on:
      - ldap
    env_file: env.sandbox
    ports:
      - '8080:8080'

  ldap:
    image: jenkinsciinfra/mock-ldap:latest
    ports:
        - 636:636
        - 389:389

  local:
    build: .
    image: accountapp:latest
    env_file: .env
    network_mode: host
    ports:
      - '8080:8080'
