version: '3'
volumes:
    elections:
services:
  ldap:
    image: jenkinsciinfra/mock-ldap:latest
    ports:
        - 636:636
        - 389:389

  sandbox:
    build: .
    image: accountapp:latest
    volumes:
      - elections:/var/log/accountapp/elections
    depends_on:
      - ldap
    env_file: env.sandbox
    environment:
        - ELECTION_CLOSE=2038/11/23
        - ELECTION_OPEN=2016/11/01
    ports:
      - '8080:8080'

  open_election:
    build: .
    image: accountapp:latest
    volumes:
      - ./fake_data:/var/log/accountapp/elections
    depends_on:
      - ldap
    env_file: env.sandbox
    environment:
        - ELECTION_CLOSE=2020/11/23
        - ELECTION_OPEN=2016/11/01
    ports:
      - '8080:8080'

  close_election:
    build: .
    image: accountapp:latest
    volumes:
      - ./fake_data:/var/log/accountapp/elections
    depends_on:
      - ldap
    env_file: env.sandbox
    environment:
        - ELECTION_CLOSE=2016/11/23
        - ELECTION_OPEN=2016/11/01
    ports:
      - '8080:8080'

  local:
    build: .
    image: accountapp:latest
    env_file: .env
    network_mode: host
    ports:
      - '8080:8080'
